bundle: kubernetes
applications:
  kafka-k8s:
    channel: latest/edge
    charm: kafka-k8s
    constraints: arch=amd64
    revision: 9
    scale: 1
  zookeeper-k8s:
    channel: latest/edge
    charm: zookeeper-k8s
    constraints: arch=amd64
    revision: 14
    scale: 3
relations:
- - kafka-k8s:zookeeper
  - zookeeper-k8s:zookeeper
