# Copyright 2023 Canonical Ltd.
# See LICENSE file for licensing details.
name: Tests (End-to-End)

on:
  pull_request:
  workflow_dispatch:
  workflow_call:
  schedule:
    - cron: '53 0 * * SAT' # Every Saturday at 00:53 UTC

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install tox
        # TODO: Consider replacing with custom image on self-hosted runner OR pinning version
        run: python3 -m pip install tox
      - name: Run linters
        run: tox run -e lint

  build:
    name: Build charms
    uses: canonical/data-platform-workflows/.github/workflows/build_charms_with_cache.yaml@v2

  e2e-tests:
    strategy:
      fail-fast: false
      max-parallel: 10
      matrix:
        tox-environments:
          - integration-e2e-basic-flow
          - integration-e2e-password-rotation
          - integration-e2e-backup
        options:
          - 
          - --tls
          - --integrator
          - --tls --integrator
        juju:
          - snap_channel: "3.4/stable"
            agent: "3.4.2"
          - snap_channel: "3.6/beta"
            agent: "3.6-beta2"
    name: ${{ matrix.tox-environments }}-${{matrix.options}}_${{ matrix.juju.agent || matrix.juju.snap_channel }}
    needs:
      - lint
      - build
    runs-on: ["self-hosted", "linux", "X64", "jammy", "large"]
    timeout-minutes: 120
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup operator environment
        # TODO: Replace with custom image on self-hosted runner
        uses: charmed-kubernetes/actions-operator@main
        with:
          provider: lxd
          juju-channel: ${{ matrix.juju.snap_channel }}
          bootstrap-options: "--agent-version ${{ matrix.juju.agent }}"
      - name: Download packed charm(s)
        uses: actions/download-artifact@v3
        with:
          name: ${{ needs.build.outputs.artifact-name }}
      - name: Select tests
        id: select-tests
        run: |
          if [ "${{ github.event_name }}" == "schedule" ]
          then
            echo Running unstable and stable tests
            echo "mark_expression=" >> $GITHUB_OUTPUT
          else
            echo Skipping unstable tests
            echo "mark_expression=not unstable" >> $GITHUB_OUTPUT
          fi
      - name: Run integration e2e tests
        run: tox run -e ${{ matrix.tox-environments }} -- -m '${{ steps.select-tests.outputs.mark_expression }}' ${{matrix.options}}
        env:
          CI_PACKED_CHARMS: ${{ needs.build.outputs.charms }}
