on:
  push:
jobs:
  integration-tests:
    name: Integration tests
    uses: ./.github/workflows/integrate.yaml

  publish:
    name: Publish bundles
    uses: ./.github/workflows/publish.yaml
    needs: [integration-tests]