name: publish bundles
on:
  workflow_call:
  workflow_dispatch:
jobs:
  publish-machine-bundle:
    name: Publish machine bundle
    runs-on: ubuntu-latest
    env:
      CHARMCRAFT_AUTH: ${{ secrets.CHARMHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          sudo snap install charmcraft --classic
          sudo apt install gnome-keyring
      - name: Pack and publish bundle
        run: |
          set -ex
          # Use a temporary directory to support publishing any of the bundles in this root dir
          BUILD_DIR=.bundle_build
          mkdir $BUILD_DIR
          cp ./releases/latest/machine/kafka/* $BUILD_DIR/
          cd $BUILD_DIR
          export CHARMCRAFT_AUTH=${{ secrets.CHARMHUB_TOKEN }}
          charmcraft pack --destructive-mode
          charmcraft upload ./*.zip
          export REVISION=$(charmcraft revisions kafka-bundle 2>&1 | awk 'NR==2 {print $1}')
          charmcraft release kafka-bundle --revision $REVISION --channel=edge
      - name: Dump logs
        if: failure()
        run: |
          printenv | sed 's;=.*;;' | sort
          awk '{print}' /home/runner/snap/charmcraft/common/cache/charmcraft/log/*.log

  publish-k8s-bundle:
    name: Publish K8s bundle
    runs-on: ubuntu-latest
    env:
      CHARMCRAFT_AUTH: ${{ secrets.CHARMHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          sudo snap install charmcraft --classic
          sudo apt install gnome-keyring
      - name: Pack and publish bundle
        run: |
          set -ex
          # Use a temporary directory to support publishing any of the bundles in this root dir
          BUILD_DIR=.bundle_build
          mkdir $BUILD_DIR
          cp ./releases/latest/k8s/kafka-k8s/* $BUILD_DIR/
          cd $BUILD_DIR
          export CHARMCRAFT_AUTH=${{ secrets.CHARMHUB_TOKEN }}
          charmcraft pack --destructive-mode
          charmcraft upload ./*.zip
          export REVISION=$(charmcraft revisions kafka-k8s-bundle 2>&1 | awk 'NR==2 {print $1}')
          charmcraft release kafka-k8s-bundle --revision $REVISION --channel=edge
      - name: Dump logs
        if: failure()
        run: |
          printenv | sed 's;=.*;;' | sort
          awk '{print}' /home/runner/snap/charmcraft/common/cache/charmcraft/log/*.log

